apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      securityContext:
        runAsUser: 2000
      containers:
      - name: myapp
        image: myapp:$CI_COMMIT_REF_SLUG
        ports:
        - containerPort: 8080
